'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NONE")>  _
        Public Property sRoofDevice() As String
            Get
                Return CType(Me("sRoofDevice"),String)
            End Get
            Set
                Me("sRoofDevice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property sInternetTimeout() As Integer
            Get
                Return CType(Me("sInternetTimeout"),Integer)
            End Get
            Set
                Me("sInternetTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sDebugKillInternet() As Boolean
            Get
                Return CType(Me("sDebugKillInternet"),Boolean)
            End Get
            Set
                Me("sDebugKillInternet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("172.20.7.41")>  _
        Public Property sUPSHost() As String
            Get
                Return CType(Me("sUPSHost"),String)
            End Get
            Set
                Me("sUPSHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("public")>  _
        Public Property sUPSCommunity() As String
            Get
                Return CType(Me("sUPSCommunity"),String)
            End Get
            Set
                Me("sUPSCommunity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".1.3.6.1.4.1.3808.1.1.1.4.1.1.0")>  _
        Public Property sUPSrequestOid() As String
            Get
                Return CType(Me("sUPSrequestOid"),String)
            End Get
            Set
                Me("sUPSrequestOid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSimulatorMode() As Boolean
            Get
                Return CType(Me("sSimulatorMode"),Boolean)
            End Get
            Set
                Me("sSimulatorMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sDebugKillUPS() As Boolean
            Get
                Return CType(Me("sDebugKillUPS"),Boolean)
            End Get
            Set
                Me("sDebugKillUPS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property sUPSTimeout() As Double
            Get
                Return CType(Me("sUPSTimeout"),Double)
            End Get
            Set
                Me("sUPSTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sRoofOpenPartly() As Double
            Get
                Return CType(Me("sRoofOpenPartly"),Double)
            End Get
            Set
                Me("sRoofOpenPartly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EYEMA-PC & CAM2")>  _
        Public Property sSwitch1Name() As String
            Get
                Return CType(Me("sSwitch1Name"),String)
            End Get
            Set
                Me("sSwitch1Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("KVM & RASPI & Solo")>  _
        Public Property sSwitch2Name() As String
            Get
                Return CType(Me("sSwitch2Name"),String)
            End Get
            Set
                Me("sSwitch2Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EzViz 1&2")>  _
        Public Property sSwitch3Name() As String
            Get
                Return CType(Me("sSwitch3Name"),String)
            End Get
            Set
                Me("sSwitch3Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10 Micron / Baader")>  _
        Public Property sSwitch4Name() As String
            Get
                Return CType(Me("sSwitch4Name"),String)
            End Get
            Set
                Me("sSwitch4Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pegasus Controller")>  _
        Public Property sSwitch5Name() As String
            Get
                Return CType(Me("sSwitch5Name"),String)
            End Get
            Set
                Me("sSwitch5Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dew Control All Sky")>  _
        Public Property sSwitch6Name() As String
            Get
                Return CType(Me("sSwitch6Name"),String)
            End Get
            Set
                Me("sSwitch6Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Spare CCD")>  _
        Public Property sSwitch7Name() As String
            Get
                Return CType(Me("sSwitch7Name"),String)
            End Get
            Set
                Me("sSwitch7Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cabinet Fan")>  _
        Public Property sSwitch8Name() As String
            Get
                Return CType(Me("sSwitch8Name"),String)
            End Get
            Set
                Me("sSwitch8Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch1Needed() As Boolean
            Get
                Return CType(Me("sSwitch1Needed"),Boolean)
            End Get
            Set
                Me("sSwitch1Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch2Needed() As Boolean
            Get
                Return CType(Me("sSwitch2Needed"),Boolean)
            End Get
            Set
                Me("sSwitch2Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch3Needed() As Boolean
            Get
                Return CType(Me("sSwitch3Needed"),Boolean)
            End Get
            Set
                Me("sSwitch3Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sSwitch4Needed() As Boolean
            Get
                Return CType(Me("sSwitch4Needed"),Boolean)
            End Get
            Set
                Me("sSwitch4Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch5Needed() As Boolean
            Get
                Return CType(Me("sSwitch5Needed"),Boolean)
            End Get
            Set
                Me("sSwitch5Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sSwitch6Needed() As Boolean
            Get
                Return CType(Me("sSwitch6Needed"),Boolean)
            End Get
            Set
                Me("sSwitch6Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch7Needed() As Boolean
            Get
                Return CType(Me("sSwitch7Needed"),Boolean)
            End Get
            Set
                Me("sSwitch7Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sSwitch8Needed() As Boolean
            Get
                Return CType(Me("sSwitch8Needed"),Boolean)
            End Get
            Set
                Me("sSwitch8Needed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Are you sure to powercycle the PC ?")>  _
        Public Property sSwitch1Warning() As String
            Get
                Return CType(Me("sSwitch1Warning"),String)
            End Get
            Set
                Me("sSwitch1Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Are you sure to powercycle the KVM / Raspberry / AAG Solo ?")>  _
        Public Property sSwitch2Warning() As String
            Get
                Return CType(Me("sSwitch2Warning"),String)
            End Get
            Set
                Me("sSwitch2Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Are you sure to powercycle EzViz 1&2 ?")>  _
        Public Property sSwitch3Warning() As String
            Get
                Return CType(Me("sSwitch3Warning"),String)
            End Get
            Set
                Me("sSwitch3Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Are you sure to powercycle the 10Micron/Power Switch ?")>  _
        Public Property sSwitch4Warning() As String
            Get
                Return CType(Me("sSwitch4Warning"),String)
            End Get
            Set
                Me("sSwitch4Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Are you sure to powercycle the Pegasus controller ?")>  _
        Public Property sSwitch5Warning() As String
            Get
                Return CType(Me("sSwitch5Warning"),String)
            End Get
            Set
                Me("sSwitch5Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property sSwitch6Warning() As String
            Get
                Return CType(Me("sSwitch6Warning"),String)
            End Get
            Set
                Me("sSwitch6Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property sSwitch7Warning() As String
            Get
                Return CType(Me("sSwitch7Warning"),String)
            End Get
            Set
                Me("sSwitch7Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Are you sure to powercycle the mount power cooling ?")>  _
        Public Property sSwitch8Warning() As String
            Get
                Return CType(Me("sSwitch8Warning"),String)
            End Get
            Set
                Me("sSwitch8Warning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("556")>  _
        Public Property sObserverHeight() As Double
            Get
                Return CType(Me("sObserverHeight"),Double)
            End Get
            Set
                Me("sObserverHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38.215506")>  _
        Public Property sObserverLatitude() As Double
            Get
                Return CType(Me("sObserverLatitude"),Double)
            End Get
            Set
                Me("sObserverLatitude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-6.6295967")>  _
        Public Property sObserverLongitude() As Double
            Get
                Return CType(Me("sObserverLongitude"),Double)
            End Get
            Set
                Me("sObserverLongitude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1013")>  _
        Public Property sObserverPressure() As Double
            Get
                Return CType(Me("sObserverPressure"),Double)
            End Get
            Set
                Me("sObserverPressure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sObserverTemperature() As Double
            Get
                Return CType(Me("sObserverTemperature"),Double)
            End Get
            Set
                Me("sObserverTemperature") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://aagsolo/cgi-bin/cgiLastData")>  _
        Public Property sWeatherURL() As String
            Get
                Return CType(Me("sWeatherURL"),String)
            End Get
            Set
                Me("sWeatherURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-5")>  _
        Public Property sWeatherCloud_Clear() As Double
            Get
                Return CType(Me("sWeatherCloud_Clear"),Double)
            End Get
            Set
                Me("sWeatherCloud_Clear") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sWeatherCloud_Cloudy() As Double
            Get
                Return CType(Me("sWeatherCloud_Cloudy"),Double)
            End Get
            Set
                Me("sWeatherCloud_Cloudy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property sWeatherCloud_Overcast() As Double
            Get
                Return CType(Me("sWeatherCloud_Overcast"),Double)
            End Get
            Set
                Me("sWeatherCloud_Overcast") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sWeatherHumidity_Dry() As Double
            Get
                Return CType(Me("sWeatherHumidity_Dry"),Double)
            End Get
            Set
                Me("sWeatherHumidity_Dry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70")>  _
        Public Property sWeatherHumidity_Normal() As Double
            Get
                Return CType(Me("sWeatherHumidity_Normal"),Double)
            End Get
            Set
                Me("sWeatherHumidity_Normal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property sWeatherHumidity_Humid() As Double
            Get
                Return CType(Me("sWeatherHumidity_Humid"),Double)
            End Get
            Set
                Me("sWeatherHumidity_Humid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sWeatherRain_Dry() As Double
            Get
                Return CType(Me("sWeatherRain_Dry"),Double)
            End Get
            Set
                Me("sWeatherRain_Dry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3000")>  _
        Public Property sWeatherRain_Wet() As Double
            Get
                Return CType(Me("sWeatherRain_Wet"),Double)
            End Get
            Set
                Me("sWeatherRain_Wet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3750")>  _
        Public Property sWeatherRain_Rain() As Double
            Get
                Return CType(Me("sWeatherRain_Rain"),Double)
            End Get
            Set
                Me("sWeatherRain_Rain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2100")>  _
        Public Property sWeatherLightness_Dark() As Double
            Get
                Return CType(Me("sWeatherLightness_Dark"),Double)
            End Get
            Set
                Me("sWeatherLightness_Dark") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property sWeatherLightness_Light() As Double
            Get
                Return CType(Me("sWeatherLightness_Light"),Double)
            End Get
            Set
                Me("sWeatherLightness_Light") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sWeatherLightness_VeryLight() As Double
            Get
                Return CType(Me("sWeatherLightness_VeryLight"),Double)
            End Get
            Set
                Me("sWeatherLightness_VeryLight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("900")>  _
        Public Property sWeatherClearDelay() As Double
            Get
                Return CType(Me("sWeatherClearDelay"),Double)
            End Get
            Set
                Me("sWeatherClearDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("L")>  _
        Public Property sCCDFilter1() As String
            Get
                Return CType(Me("sCCDFilter1"),String)
            End Get
            Set
                Me("sCCDFilter1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("H")>  _
        Public Property sCCDFilter2() As String
            Get
                Return CType(Me("sCCDFilter2"),String)
            End Get
            Set
                Me("sCCDFilter2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LPS")>  _
        Public Property sCCDFilter3() As String
            Get
                Return CType(Me("sCCDFilter3"),String)
            End Get
            Set
                Me("sCCDFilter3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LENH")>  _
        Public Property sCCDFilter4() As String
            Get
                Return CType(Me("sCCDFilter4"),String)
            End Get
            Set
                Me("sCCDFilter4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("V")>  _
        Public Property sCCDFilter5() As String
            Get
                Return CType(Me("sCCDFilter5"),String)
            End Get
            Set
                Me("sCCDFilter5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sAlarmPlay() As Boolean
            Get
                Return CType(Me("sAlarmPlay"),Boolean)
            End Get
            Set
                Me("sAlarmPlay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\RoboticObs\best_wake_up_sound.wav")>  _
        Public Property sAlarmSound() As String
            Get
                Return CType(Me("sAlarmSound"),String)
            End Get
            Set
                Me("sAlarmSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\RoboObsLog\")>  _
        Public Property sLogLocation() As String
            Get
                Return CType(Me("sLogLocation"),String)
            End Get
            Set
                Me("sLogLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EYEMA-OBS")>  _
        Public Property sObservatoryName() As String
            Get
                Return CType(Me("sObservatoryName"),String)
            End Get
            Set
                Me("sObservatoryName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-445733727")>  _
        Public Property sTelegramErrorID() As String
            Get
                Return CType(Me("sTelegramErrorID"),String)
            End Get
            Set
                Me("sTelegramErrorID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-410999015")>  _
        Public Property sTelegramSessionID() As String
            Get
                Return CType(Me("sTelegramSessionID"),String)
            End Get
            Set
                Me("sTelegramSessionID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BRIEF")>  _
        Public Property sTelegramLoggingType() As String
            Get
                Return CType(Me("sTelegramLoggingType"),String)
            End Get
            Set
                Me("sTelegramLoggingType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("965192245:AAFuAzlsjUkWX5eLb6GC0zT5Sgj_oSpgLo0")>  _
        Public Property sTelegramBOT() As String
            Get
                Return CType(Me("sTelegramBOT"),String)
            End Get
            Set
                Me("sTelegramBOT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FULL")>  _
        Public Property sLogType() As String
            Get
                Return CType(Me("sLogType"),String)
            End Get
            Set
                Me("sLogType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sCCDFocusSubFrame() As Double
            Get
                Return CType(Me("sCCDFocusSubFrame"),Double)
            End Get
            Set
                Me("sCCDFocusSubFrame") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6248")>  _
        Public Property sCCDSensorSizeX() As Integer
            Get
                Return CType(Me("sCCDSensorSizeX"),Integer)
            End Get
            Set
                Me("sCCDSensorSizeX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4176")>  _
        Public Property sCCDSensorSizeY() As Integer
            Get
                Return CType(Me("sCCDSensorSizeY"),Integer)
            End Get
            Set
                Me("sCCDSensorSizeY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.868")>  _
        Public Property sCCDImageScale() As Double
            Get
                Return CType(Me("sCCDImageScale"),Double)
            End Get
            Set
                Me("sCCDImageScale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property sWeatherTimeout() As Double
            Get
                Return CType(Me("sWeatherTimeout"),Double)
            End Get
            Set
                Me("sWeatherTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\RoboObsImages\")>  _
        Public Property sCCDImagePath() As String
            Get
                Return CType(Me("sCCDImagePath"),String)
            End Get
            Set
                Me("sCCDImagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ASCOM.SoftwareBisque.Telescope")>  _
        Public Property sMountDevice() As String
            Get
                Return CType(Me("sMountDevice"),String)
            End Get
            Set
                Me("sMountDevice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sCCDPlateSolveExposure() As Double
            Get
                Return CType(Me("sCCDPlateSolveExposure"),Double)
            End Get
            Set
                Me("sCCDPlateSolveExposure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property sCCDPlateSolveMaxError() As Double
            Get
                Return CType(Me("sCCDPlateSolveMaxError"),Double)
            End Get
            Set
                Me("sCCDPlateSolveMaxError") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2x2")>  _
        Public Property sCCDPlateSolveBinning() As String
            Get
                Return CType(Me("sCCDPlateSolveBinning"),String)
            End Get
            Set
                Me("sCCDPlateSolveBinning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property sCCDPlateSolveNbrTries() As Integer
            Get
                Return CType(Me("sCCDPlateSolveNbrTries"),Integer)
            End Get
            Set
                Me("sCCDPlateSolveNbrTries") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sAutoStart() As Boolean
            Get
                Return CType(Me("sAutoStart"),Boolean)
            End Get
            Set
                Me("sAutoStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SAFE")>  _
        Public Property sDebugCloud() As String
            Get
                Return CType(Me("sDebugCloud"),String)
            End Get
            Set
                Me("sDebugCloud") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DARK")>  _
        Public Property sDebugLight() As String
            Get
                Return CType(Me("sDebugLight"),String)
            End Get
            Set
                Me("sDebugLight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sDebugAAGData() As Boolean
            Get
                Return CType(Me("sDebugAAGData"),Boolean)
            End Get
            Set
                Me("sDebugAAGData") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sDebugSunMoonCoordinates() As Boolean
            Get
                Return CType(Me("sDebugSunMoonCoordinates"),Boolean)
            End Get
            Set
                Me("sDebugSunMoonCoordinates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property SDebugSunAltitude() As Double
            Get
                Return CType(Me("SDebugSunAltitude"),Double)
            End Get
            Set
                Me("SDebugSunAltitude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-20")>  _
        Public Property SDebugMoonAltitude() As Double
            Get
                Return CType(Me("SDebugMoonAltitude"),Double)
            End Get
            Set
                Me("SDebugMoonAltitude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SETTING")>  _
        Public Property SDebugSunRisingSetting() As String
            Get
                Return CType(Me("SDebugSunRisingSetting"),String)
            End Get
            Set
                Me("SDebugSunRisingSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RISING")>  _
        Public Property SDebugMoonRisingSetting() As String
            Get
                Return CType(Me("SDebugMoonRisingSetting"),String)
            End Get
            Set
                Me("SDebugMoonRisingSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sSunOpenRoof() As Double
            Get
                Return CType(Me("sSunOpenRoof"),Double)
            End Get
            Set
                Me("sSunOpenRoof") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property sSunDuskFlats() As Double
            Get
                Return CType(Me("sSunDuskFlats"),Double)
            End Get
            Set
                Me("sSunDuskFlats") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-12")>  _
        Public Property sSunStartRun() As Double
            Get
                Return CType(Me("sSunStartRun"),Double)
            End Get
            Set
                Me("sSunStartRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-12")>  _
        Public Property sSunStopRun() As Double
            Get
                Return CType(Me("sSunStopRun"),Double)
            End Get
            Set
                Me("sSunStopRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-4")>  _
        Public Property sSunDawnFlats() As Double
            Get
                Return CType(Me("sSunDawnFlats"),Double)
            End Get
            Set
                Me("sSunDawnFlats") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property sRoofOpenTimeout() As Double
            Get
                Return CType(Me("sRoofOpenTimeout"),Double)
            End Get
            Set
                Me("sRoofOpenTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sObjectAltLimitEast() As Double
            Get
                Return CType(Me("sObjectAltLimitEast"),Double)
            End Get
            Set
                Me("sObjectAltLimitEast") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property sObjectAltLimitWest() As Double
            Get
                Return CType(Me("sObjectAltLimitWest"),Double)
            End Get
            Set
                Me("sObjectAltLimitWest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sAlarmRepeat() As Integer
            Get
                Return CType(Me("sAlarmRepeat"),Integer)
            End Get
            Set
                Me("sAlarmRepeat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sDebugKillAAG() As Boolean
            Get
                Return CType(Me("sDebugKillAAG"),Boolean)
            End Get
            Set
                Me("sDebugKillAAG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sCCDFocusEveryXImages() As Integer
            Get
                Return CType(Me("sCCDFocusEveryXImages"),Integer)
            End Get
            Set
                Me("sCCDFocusEveryXImages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
        Public Property sCCDFocusEveryXDegrees() As Double
            Get
                Return CType(Me("sCCDFocusEveryXDegrees"),Double)
            End Get
            Set
                Me("sCCDFocusEveryXDegrees") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sCCDDithering() As Boolean
            Get
                Return CType(Me("sCCDDithering"),Boolean)
            End Get
            Set
                Me("sCCDDithering") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sCCDDitheringAmount() As Integer
            Get
                Return CType(Me("sCCDDitheringAmount"),Integer)
            End Get
            Set
                Me("sCCDDitheringAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sCCDFocusMeridianFlip() As Boolean
            Get
                Return CType(Me("sCCDFocusMeridianFlip"),Boolean)
            End Get
            Set
                Me("sCCDFocusMeridianFlip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM13")>  _
        Public Property sSnapCapSerialPort() As String
            Get
                Return CType(Me("sSnapCapSerialPort"),String)
            End Get
            Set
                Me("sSnapCapSerialPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SERIAL")>  _
        Public Property sCoverMethod() As String
            Get
                Return CType(Me("sCoverMethod"),String)
            End Get
            Set
                Me("sCoverMethod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sDisableSafetyCheck() As Boolean
            Get
                Return CType(Me("sDisableSafetyCheck"),Boolean)
            End Get
            Set
                Me("sDisableSafetyCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sCCDFocusDefExp() As Double
            Get
                Return CType(Me("sCCDFocusDefExp"),Double)
            End Get
            Set
                Me("sCCDFocusDefExp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property sCCDFocusSamples() As Integer
            Get
                Return CType(Me("sCCDFocusSamples"),Integer)
            End Get
            Set
                Me("sCCDFocusSamples") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSunDuskFlatsNeeded() As Boolean
            Get
                Return CType(Me("sSunDuskFlatsNeeded"),Boolean)
            End Get
            Set
                Me("sSunDuskFlatsNeeded") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSunDawnFlatsNeeded() As Boolean
            Get
                Return CType(Me("sSunDawnFlatsNeeded"),Boolean)
            End Get
            Set
                Me("sSunDawnFlatsNeeded") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\SynologyDrive\e-eye data\")>  _
        Public Property sSynologyPath() As String
            Get
                Return CType(Me("sSynologyPath"),String)
            End Get
            Set
                Me("sSynologyPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property sSMARTTimeout() As Double
            Get
                Return CType(Me("sSMARTTimeout"),Double)
            End Get
            Set
                Me("sSMARTTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\RoboticSentinel\RoboticSentinel.exe")>  _
        Public Property sSentinelEXE() As String
            Get
                Return CType(Me("sSentinelEXE"),String)
            End Get
            Set
                Me("sSentinelEXE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sTurnOffCompletely() As Boolean
            Get
                Return CType(Me("sTurnOffCompletely"),Boolean)
            End Get
            Set
                Me("sTurnOffCompletely") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DEEPSKY")>  _
        Public Property sObservationProgram() As String
            Get
                Return CType(Me("sObservationProgram"),String)
            End Get
            Set
                Me("sObservationProgram") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sMoonIgnore() As Boolean
            Get
                Return CType(Me("sMoonIgnore"),Boolean)
            End Get
            Set
                Me("sMoonIgnore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sCCDBlindSolve() As Boolean
            Get
                Return CType(Me("sCCDBlindSolve"),Boolean)
            End Get
            Set
                Me("sCCDBlindSolve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sMountMeridianFlip() As Boolean
            Get
                Return CType(Me("sMountMeridianFlip"),Boolean)
            End Get
            Set
                Me("sMountMeridianFlip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sMountMeridianFlipMinutes() As Double
            Get
                Return CType(Me("sMountMeridianFlipMinutes"),Double)
            End Get
            Set
                Me("sMountMeridianFlipMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sToolsOpenRoof() As Boolean
            Get
                Return CType(Me("sToolsOpenRoof"),Boolean)
            End Get
            Set
                Me("sToolsOpenRoof") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sDebugMoonIllumination() As Double
            Get
                Return CType(Me("sDebugMoonIllumination"),Double)
            End Get
            Set
                Me("sDebugMoonIllumination") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sUPSNotPresent() As Boolean
            Get
                Return CType(Me("sUPSNotPresent"),Boolean)
            End Get
            Set
                Me("sUPSNotPresent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sCCDCoolingEnabled() As Boolean
            Get
                Return CType(Me("sCCDCoolingEnabled"),Boolean)
            End Get
            Set
                Me("sCCDCoolingEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-5")>  _
        Public Property sCCDCoolingTemp() As Double
            Get
                Return CType(Me("sCCDCoolingTemp"),Double)
            End Get
            Set
                Me("sCCDCoolingTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("106000")>  _
        Public Property sCCDFocusDefaultPosition() As Double
            Get
                Return CType(Me("sCCDFocusDefaultPosition"),Double)
            End Get
            Set
                Me("sCCDFocusDefaultPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public Property sCCDFocusDefaultFork() As Double
            Get
                Return CType(Me("sCCDFocusDefaultFork"),Double)
            End Get
            Set
                Me("sCCDFocusDefaultFork") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property sSMARTCycle() As Double
            Get
                Return CType(Me("sSMARTCycle"),Double)
            End Get
            Set
                Me("sSMARTCycle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\7-Zip\7z.exe")>  _
        Public Property s7ZipLocation() As String
            Get
                Return CType(Me("s7ZipLocation"),String)
            End Get
            Set
                Me("s7ZipLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sSentinelAutostart() As Boolean
            Get
                Return CType(Me("sSentinelAutostart"),Boolean)
            End Get
            Set
                Me("sSentinelAutostart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property sAutoFlatMinExp() As Double
            Get
                Return CType(Me("sAutoFlatMinExp"),Double)
            End Get
            Set
                Me("sAutoFlatMinExp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sAutoFlatMaxExp() As Double
            Get
                Return CType(Me("sAutoFlatMaxExp"),Double)
            End Get
            Set
                Me("sAutoFlatMaxExp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15000")>  _
        Public Property sAutoFlatMinADU() As Double
            Get
                Return CType(Me("sAutoFlatMinADU"),Double)
            End Get
            Set
                Me("sAutoFlatMinADU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35000")>  _
        Public Property sAutoFlatMaxADU() As Double
            Get
                Return CType(Me("sAutoFlatMaxADU"),Double)
            End Get
            Set
                Me("sAutoFlatMaxADU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property sAutoFlatAlt() As Double
            Get
                Return CType(Me("sAutoFlatAlt"),Double)
            End Get
            Set
                Me("sAutoFlatAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property sAutoFlatAz() As Double
            Get
                Return CType(Me("sAutoFlatAz"),Double)
            End Get
            Set
                Me("sAutoFlatAz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1x1")>  _
        Public Property sAutoFlatBin() As String
            Get
                Return CType(Me("sAutoFlatBin"),String)
            End Get
            Set
                Me("sAutoFlatBin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("L")>  _
        Public Property sAutoFlatFilter() As String
            Get
                Return CType(Me("sAutoFlatFilter"),String)
            End Get
            Set
                Me("sAutoFlatFilter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/spreadsheets/d/e/2PACX-1vSyphtUrAM-tldhj0d4EH6BAbyPrMbfPq"& _ 
            "4UZ5AANyacd9OL8WAY4Ef0mZ_xbpIC7Bj3GhJuv6oSMyAM/pub?gid=316386585&single=true&out"& _ 
            "put=tsv")>  _
        Public Property SHADSURL() As String
            Get
                Return CType(Me("SHADSURL"),String)
            End Get
            Set
                Me("SHADSURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sMoonStartCooldown() As Boolean
            Get
                Return CType(Me("sMoonStartCooldown"),Boolean)
            End Get
            Set
                Me("sMoonStartCooldown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sSwitch1Startup() As Double
            Get
                Return CType(Me("sSwitch1Startup"),Double)
            End Get
            Set
                Me("sSwitch1Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sSwitch2Startup() As Double
            Get
                Return CType(Me("sSwitch2Startup"),Double)
            End Get
            Set
                Me("sSwitch2Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sSwitch3Startup() As Double
            Get
                Return CType(Me("sSwitch3Startup"),Double)
            End Get
            Set
                Me("sSwitch3Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property sSwitch4Startup() As Double
            Get
                Return CType(Me("sSwitch4Startup"),Double)
            End Get
            Set
                Me("sSwitch4Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sSwitch5Startup() As Double
            Get
                Return CType(Me("sSwitch5Startup"),Double)
            End Get
            Set
                Me("sSwitch5Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sSwitch6Startup() As Double
            Get
                Return CType(Me("sSwitch6Startup"),Double)
            End Get
            Set
                Me("sSwitch6Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sSwitch7Startup() As Double
            Get
                Return CType(Me("sSwitch7Startup"),Double)
            End Get
            Set
                Me("sSwitch7Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sSwitch8Startup() As Double
            Get
                Return CType(Me("sSwitch8Startup"),Double)
            End Get
            Set
                Me("sSwitch8Startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch1Mount() As Boolean
            Get
                Return CType(Me("sSwitch1Mount"),Boolean)
            End Get
            Set
                Me("sSwitch1Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch2Mount() As Boolean
            Get
                Return CType(Me("sSwitch2Mount"),Boolean)
            End Get
            Set
                Me("sSwitch2Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch3Mount() As Boolean
            Get
                Return CType(Me("sSwitch3Mount"),Boolean)
            End Get
            Set
                Me("sSwitch3Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sSwitch4Mount() As Boolean
            Get
                Return CType(Me("sSwitch4Mount"),Boolean)
            End Get
            Set
                Me("sSwitch4Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch5Mount() As Boolean
            Get
                Return CType(Me("sSwitch5Mount"),Boolean)
            End Get
            Set
                Me("sSwitch5Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch6Mount() As Boolean
            Get
                Return CType(Me("sSwitch6Mount"),Boolean)
            End Get
            Set
                Me("sSwitch6Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch7Mount() As Boolean
            Get
                Return CType(Me("sSwitch7Mount"),Boolean)
            End Get
            Set
                Me("sSwitch7Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sSwitch8Mount() As Boolean
            Get
                Return CType(Me("sSwitch8Mount"),Boolean)
            End Get
            Set
                Me("sSwitch8Mount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sHADSMag8() As String
            Get
                Return CType(Me("sHADSMag8"),String)
            End Get
            Set
                Me("sHADSMag8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property sHADSMag9() As String
            Get
                Return CType(Me("sHADSMag9"),String)
            End Get
            Set
                Me("sHADSMag9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property sHADSMag10() As String
            Get
                Return CType(Me("sHADSMag10"),String)
            End Get
            Set
                Me("sHADSMag10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property sHADSMag11() As String
            Get
                Return CType(Me("sHADSMag11"),String)
            End Get
            Set
                Me("sHADSMag11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property sHADSMag12() As String
            Get
                Return CType(Me("sHADSMag12"),String)
            End Get
            Set
                Me("sHADSMag12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property sHADSMag13() As String
            Get
                Return CType(Me("sHADSMag13"),String)
            End Get
            Set
                Me("sHADSMag13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property sHADSMag14() As String
            Get
                Return CType(Me("sHADSMag14"),String)
            End Get
            Set
                Me("sHADSMag14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property sHADSMag15() As String
            Get
                Return CType(Me("sHADSMag15"),String)
            End Get
            Set
                Me("sHADSMag15") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-25")>  _
        Public Property sHADSDECCutOff() As Double
            Get
                Return CType(Me("sHADSDECCutOff"),Double)
            End Get
            Set
                Me("sHADSDECCutOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ASI ZWO2600MC")>  _
        Public Property sCCDName() As String
            Get
                Return CType(Me("sCCDName"),String)
            End Get
            Set
                Me("sCCDName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property sCCDColorCamera() As Boolean
            Get
                Return CType(Me("sCCDColorCamera"),Boolean)
            End Get
            Set
                Me("sCCDColorCamera") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("890")>  _
        Public Property sTelescopeFocalLength() As Integer
            Get
                Return CType(Me("sTelescopeFocalLength"),Integer)
            End Get
            Set
                Me("sTelescopeFocalLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Takahashi CCA250-3.6")>  _
        Public Property sTelescopeName() As String
            Get
                Return CType(Me("sTelescopeName"),String)
            End Get
            Set
                Me("sTelescopeName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250")>  _
        Public Property sTelescopeAparture() As Integer
            Get
                Return CType(Me("sTelescopeAparture"),Integer)
            End Get
            Set
                Me("sTelescopeAparture") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3.76")>  _
        Public Property sCCDPixelSize() As Double
            Get
                Return CType(Me("sCCDPixelSize"),Double)
            End Get
            Set
                Me("sCCDPixelSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property sCoverDevice() As String
            Get
                Return CType(Me("sCoverDevice"),String)
            End Get
            Set
                Me("sCoverDevice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property sSwitchDevice() As String
            Get
                Return CType(Me("sSwitchDevice"),String)
            End Get
            Set
                Me("sSwitchDevice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://user:secret@172.20.7.49/?cmd=5&p=1&a1=1&a2=0&s=2")>  _
        Public Property sMountStartupLink() As String
            Get
                Return CType(Me("sMountStartupLink"),String)
            End Get
            Set
                Me("sMountStartupLink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sCCDFocusClosedLoopSlew() As Boolean
            Get
                Return CType(Me("sCCDFocusClosedLoopSlew"),Boolean)
            End Get
            Set
                Me("sCCDFocusClosedLoopSlew") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sMoonAltitudeAlwaysSafe() As Double
            Get
                Return CType(Me("sMoonAltitudeAlwaysSafe"),Double)
            End Get
            Set
                Me("sMoonAltitudeAlwaysSafe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sMoonPhaseAlwaysSafe() As Double
            Get
                Return CType(Me("sMoonPhaseAlwaysSafe"),Double)
            End Get
            Set
                Me("sMoonPhaseAlwaysSafe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property sMoonPhaseLimitLow() As Double
            Get
                Return CType(Me("sMoonPhaseLimitLow"),Double)
            End Get
            Set
                Me("sMoonPhaseLimitLow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property sMoonAltitudeLimitLow() As Double
            Get
                Return CType(Me("sMoonAltitudeLimitLow"),Double)
            End Get
            Set
                Me("sMoonAltitudeLimitLow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35")>  _
        Public Property sMoonStartCooldownLow() As Double
            Get
                Return CType(Me("sMoonStartCooldownLow"),Double)
            End Get
            Set
                Me("sMoonStartCooldownLow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sMoonAltitudeLimitHigh() As Double
            Get
                Return CType(Me("sMoonAltitudeLimitHigh"),Double)
            End Get
            Set
                Me("sMoonAltitudeLimitHigh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property sMoonStartCooldownHigh() As Double
            Get
                Return CType(Me("sMoonStartCooldownHigh"),Double)
            End Get
            Set
                Me("sMoonStartCooldownHigh") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.RoboticObs.My.MySettings
            Get
                Return Global.RoboticObs.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
